[generate]
deps=["_site/index.html", "_site/js", "_site/css"]

["_site/index.html"]
deps=["post_metadata.json"]
exec="node src/make_site.js"

["_site/js"]
exec="mkdir -p _site   &&  cp -r layout/js $@"

["_site/css"]
exec="mkdir -p _site   &&  cp -r layout/css $@"

["post_metadata.json"]
exec="node src/extract_from_db.js"

[start]
deps=["generate"]
exec="cd _site && live-server"

[clean]
exec="rm -rf post_metadata.json content _site"

[fix]
exec="standard --fix --ignore layout/js/tex-svg-full.js --ignore layout/js/equation.js"
